SET sql_mode = '';
DROP DATABASE IF EXISTS nutri_db;

CREATE DATABASE nutri_db;
USE nutri_db;

CREATE TABLE patients (
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  patient_name VARCHAR(30) NOT NULL,
  user_name VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE healthStats(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  patient_id INTEGER(10) NOT NULL,
  diet_recommendation VARCHAR(30) NOT NULL,
  risk_factor VARCHAR(30) NOT NULL,
  diet_restriction VARCHAR(30) NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE doctors(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  patient_id VARCHAR(30) NOT NULL,
  doctor_name VARCHAR(30) NOT NULL,
  user_name VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE savedRecipes(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  patient_id VARCHAR(30) NOT NULL,
  recipe VARCHAR(200),
  favorite BOOLEAN NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);

